### ISSUE TITLE
Feedback; testing on site with and without proper records. All green.

### ISSUE THREAD

**Issue by oldrup** [Zodiac1978/dns-info#5]
Not an issue, just unsure where else to provide feedback.

Here is a screenshot from my personal blog; SPF, DKIM and DMARC records set:
![image](https://github.com/Zodiac1978/dns-info/assets/17141205/3ad82de9-4d25-489a-9276-cf3e306177f1)

Here is a screenshot from a test-site, with no mail-related records set:
![image](https://github.com/Zodiac1978/dns-info/assets/17141205/aef25860-6d6f-4a66-9dea-e0a0ee721b18)

The info is also included in site-health text export.
![image](https://github.com/Zodiac1978/dns-info/assets/17141205/303ede33-2b07-4f08-ad4f-681a9acc4d1a)

I tested on WP 6.4.x, PHP 8.1 and PHP 8.2; WP debug enabled; no warnings or errors.

All the information is available on the DNS server anyway, so I don't see any security concerns related to making the information readily available in the Site Health tool; it just makes mail-related troubleshooting easier.

I'd love to see this info added to the core Site Health tool at some point—nice work 👏👏👏

**Comment by Zodiac1978** [comment]
Thanks for testing!
